# .readthedocs.yaml
version: 2

# Build environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # install dependencies needed to build the docs
      - pip install -r requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
